export const CHECK_AUTH = 'CHECK_AUTH';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const TODO_FETCH_START = 'TODO_FETCH_START';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const TODO_FETCH_FAIL = 'TODO_FETCH_FAIL';

export const TODO_DELETE_START = 'TODO_DELETE_START';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';

export const TODO_ADD_START = 'TODO_ADD_START';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_FAIL = 'TODO_ADD_FAIL';

export const TODO_CHECKED_START = 'TODO_CHECKED_START';
export const TODO_CHECKED_SUCCESS = 'TODO_CHECKED_SUCCESS';
export const TODO_CHECKED_FAIL = 'TODO_CHECKED_FAIL';

export const TODO_CLEAR_ERROR = 'TODO_CLEAR_ERROR';